### ISSUE TITLE
SafeConfigParser with ExtendedInterpolation

### ISSUE THREAD

**Issue by jpmn** [maxzheng/localconfig#3]
It would be nice to be able to configure the inner parser in `LocalConfig`. I am using `ExtendedInterpolation` from `configparser` to share config options between sections of my configuraiton file.

https://docs.python.org/3.3/library/configparser.html#configparser.ExtendedInterpolation

```
[server]
host=0.0.0.0
port=5000

[client]
server_host=${server:host}
server_port=${server:port}
```

**Comment by maxzheng** [comment]
@jpmn Just published localconfig 1.1.2 that allows you to specify the interpolation instance. See example at https://github.com/maxzheng/localconfig/blob/master/test/test_manager.py#L250

Let me know if you have problems using that.
