### ISSUE TITLE
TypeError: super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by JolleJolles** [maxzheng/localconfig#4]
I get the above error when I try to import localconfig. Do you know how to fix this?

**Comment by maxzheng** [comment]
That error comes from using localconfig in Python 2. Localconfig only supports 3.6 or higher. Can u upgrade ur Python?

**Comment by JolleJolles** [comment]
On my other computer with python 2 it does work somehow, see attached screenshot. Is that perhaps because of a previous version and if so is there a way to download that? I'd rather not update my python.
<img width="506" alt="screen shot 2018-07-17 at 07 04 42" src="https://user-images.githubusercontent.com/8775649/42797491-caabaa54-898f-11e8-897d-6402127c508d.png">

**Comment by maxzheng** [comment]
The last version with Python 2 support is 0.4.2, so you can pin to that and it should work.
Alternatively, you can also figure out which version you have installed currently by using `pip list`
